rizin_app/urls.py
from django.urls import path
from . import views

app_name = 'rizin_app'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('player_list/', views.player_list, name='player_list'),
    path('bantamrank_create/', views.BantamrankCreateView.as_view(), name='bantamrank_create'),
    path('featherrank_create/', views.FeatherrankCreateView.as_view(), name='featherrank_create'),
    path('rightrank_create/', views.RightrankCreateView.as_view(), name='rightrank_create'),
    path('bantamrank_list/', views.BantamrankListView.as_view(), name='bantamrank_list'),
    path('featherrank_list/', views.FeatherrankListView.as_view(), name='featherrank_list'),
    path('rightrank_list/', views.RightrankListView.as_view(), name='rightrank_list'),
]

rizin_rank/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path,include

from . import settings_common,settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('rizin_app.urls')),
]

urlpatterns += static(settings_common.MEDIA_URL,document_root=settings_dev.MEDIA_ROOT)

rizin_app/models.py
from django.db import models

class BantamPlayer(models.Model):

    name = models.CharField(verbose_name='名前',max_length=20)
    nickname = models.CharField(verbose_name='ニックネーム',max_length=20,null=True,blank=True)
    photo = models.ImageField(verbose_name='写真')
    birthday = models.CharField(verbose_name='生年月日',max_length=20,null=True)
    nationality = models.CharField(verbose_name='国籍',max_length=20)
    height = models.IntegerField(verbose_name='身長')
    mma_record = models.CharField(verbose_name='MMA戦績',max_length=20)
    rizin_record = models.CharField(verbose_name='RIZIN戦績',max_length=20)

    class Meta:
        verbose_name_plural = 'BantamPlayer'

    def __str__(self):
        return self.name

class FeatherPlayer(models.Model):

    name = models.CharField(verbose_name='名前',max_length=20)
    nickname = models.CharField(verbose_name='ニックネーム',max_length=20,null=True,blank=True)
    photo = models.ImageField(verbose_name='写真')
    birthday = models.CharField(verbose_name='生年月日',max_length=20,null=True)
    nationality = models.CharField(verbose_name='国籍',max_length=20)
    height = models.IntegerField(verbose_name='身長')
    mma_record = models.CharField(verbose_name='MMA戦績',max_length=20)
    rizin_record = models.CharField(verbose_name='RIZIN戦績',max_length=20)

    class Meta:
        verbose_name_plural = 'FeatherPlayer'

    def __str__(self):
        return self.name

class RightPlayer(models.Model):

    name = models.CharField(verbose_name='名前',max_length=20)
    nickname = models.CharField(verbose_name='ニックネーム',max_length=20,null=True,blank=True)
    photo = models.ImageField(verbose_name='写真')
    birthday = models.CharField(verbose_name='生年月日',max_length=20,null=True)
    nationality = models.CharField(verbose_name='国籍',max_length=20)
    height = models.IntegerField(verbose_name='身長')
    mma_record = models.CharField(verbose_name='MMA戦績',max_length=20)
    rizin_record = models.CharField(verbose_name='RIZIN戦績',max_length=20)

    class Meta:
        verbose_name_plural = 'RightPlayer'

    def __str__(self):
        return self.name


class BantamRank(models.Model):
    user = models.CharField(verbose_name='作成者', max_length=20)
    one = models.ForeignKey(BantamPlayer,related_name='bantamrank_one',on_delete=models.PROTECT)
    two = models.ForeignKey(BantamPlayer,related_name='bantamrank_two',on_delete=models.PROTECT)
    three = models.ForeignKey(BantamPlayer,related_name='bantamrank_three',on_delete=models.PROTECT)
    four = models.ForeignKey(BantamPlayer,related_name='bantamrank_four',on_delete=models.PROTECT)
    five = models.ForeignKey(BantamPlayer,related_name='bantamrank_five',on_delete=models.PROTECT)
    six = models.ForeignKey(BantamPlayer,related_name='bantamrank_six',on_delete=models.PROTECT)
    seven = models.ForeignKey(BantamPlayer,related_name='bantamrank_seven',on_delete=models.PROTECT)
    eight = models.ForeignKey(BantamPlayer,related_name='bantamrank_eight',on_delete=models.PROTECT)
    nine = models.ForeignKey(BantamPlayer,related_name='bantamrank_nine',on_delete=models.PROTECT)
    ten = models.ForeignKey(BantamPlayer,related_name='bantamrank_ten',on_delete=models.PROTECT)
    created_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)

    class Meta:
        verbose_name_plural = 'BantamRank'

    def __str__(self):
        return self.user,self.created_at

class FeatherRank(models.Model):
    user = models.CharField(verbose_name='作成者', max_length=20)
    one = models.ForeignKey(FeatherPlayer,related_name='featherrank_one',on_delete=models.PROTECT)
    two = models.ForeignKey(FeatherPlayer,related_name='featherrank_two',on_delete=models.PROTECT)
    three = models.ForeignKey(FeatherPlayer,related_name='featherrank_three',on_delete=models.PROTECT)
    four = models.ForeignKey(FeatherPlayer,related_name='featherrank_four',on_delete=models.PROTECT)
    five = models.ForeignKey(FeatherPlayer,related_name='featherrank_five',on_delete=models.PROTECT)
    six = models.ForeignKey(FeatherPlayer,related_name='featherrank_six',on_delete=models.PROTECT)
    seven = models.ForeignKey(FeatherPlayer,related_name='featherrank_seven',on_delete=models.PROTECT)
    eight = models.ForeignKey(FeatherPlayer,related_name='featherrank_eight',on_delete=models.PROTECT)
    nine = models.ForeignKey(FeatherPlayer,related_name='featherrank_nine',on_delete=models.PROTECT)
    ten = models.ForeignKey(FeatherPlayer,related_name='featherrank_ten',on_delete=models.PROTECT)
    created_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)

    class Meta:
        verbose_name_plural = 'FeatherRank'

    def __str__(self):
        return self.user,self.created_at

class RightRank(models.Model):
    user = models.CharField(verbose_name='作成者', max_length=20)
    one = models.ForeignKey(RightPlayer,related_name='right_one',on_delete=models.PROTECT)
    two = models.ForeignKey(RightPlayer,related_name='right_two',on_delete=models.PROTECT)
    three = models.ForeignKey(RightPlayer,related_name='right_three',on_delete=models.PROTECT)
    four = models.ForeignKey(RightPlayer,related_name='right_four',on_delete=models.PROTECT)
    five = models.ForeignKey(RightPlayer,related_name='right_five',on_delete=models.PROTECT)
    six = models.ForeignKey(RightPlayer,related_name='right_six',on_delete=models.PROTECT)
    seven = models.ForeignKey(RightPlayer,related_name='right_seven',on_delete=models.PROTECT)
    eight = models.ForeignKey(RightPlayer,related_name='right_eight',on_delete=models.PROTECT)
    nine = models.ForeignKey(RightPlayer,related_name='right_nine',on_delete=models.PROTECT)
    ten = models.ForeignKey(RightPlayer,related_name='right_ten',on_delete=models.PROTECT)
    created_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)

    class Meta:
        verbose_name_plural = 'RightRank'

    def __str__(self):
        return self.user,self.created_at

rizin_app/forms.py
from .models import BantamRank,BantamPlayer,FeatherRank,FeatherPlayer,RightPlayer,RightRank
from django import forms

class BantamrankCreateForm(forms.ModelForm):
    one = forms.ModelChoiceField(label='1位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='1位を選択')
    two = forms.ModelChoiceField(label='2位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='2位を選択')
    three = forms.ModelChoiceField(label='3位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='3位を選択')
    four = forms.ModelChoiceField(label='4位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='4位を選択')
    five = forms.ModelChoiceField(label='5位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='5位を選択')
    six = forms.ModelChoiceField(label='6位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='6位を選択')
    seven = forms.ModelChoiceField(label='7位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='7位を選択')
    eight = forms.ModelChoiceField(label='8位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='8位を選択')
    nine = forms.ModelChoiceField(label='9位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='9位を選択')
    ten = forms.ModelChoiceField(label='10位',queryset=BantamPlayer.objects.all(),widget=forms.Select,empty_label='10位を選択')

    class Meta:
        model = BantamRank

        fields = ('user','one','two','three','four','five','six','seven','eight','nine','ten',)
        widget = {'user': forms.TextInput(),}

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['user'].widget.attrs['class'] = 'form-control'
        self.fields['user'].widget.attrs['placeholder'] = '作成者'
        self.fields['user'].widget.attrs['maxlength'] = '20'


class FeatherrankCreateForm(forms.ModelForm):
    one = forms.ModelChoiceField(label='1位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                 empty_label='1位を選択')
    two = forms.ModelChoiceField(label='2位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                 empty_label='2位を選択')
    three = forms.ModelChoiceField(label='3位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                   empty_label='3位を選択')
    four = forms.ModelChoiceField(label='4位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                  empty_label='4位を選択')
    five = forms.ModelChoiceField(label='5位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                  empty_label='5位を選択')
    six = forms.ModelChoiceField(label='6位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                 empty_label='6位を選択')
    seven = forms.ModelChoiceField(label='7位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                   empty_label='7位を選択')
    eight = forms.ModelChoiceField(label='8位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                   empty_label='8位を選択')
    nine = forms.ModelChoiceField(label='9位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                  empty_label='9位を選択')
    ten = forms.ModelChoiceField(label='10位', queryset=FeatherPlayer.objects.all(), widget=forms.Select,
                                 empty_label='10位を選択')

    class Meta:
        model = FeatherRank

        fields = ('user', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',)
        widget = {'user': forms.TextInput(), }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs['class'] = 'form-control'
        self.fields['user'].widget.attrs['placeholder'] = '作成者'
        self.fields['user'].widget.attrs['maxlength'] = '20'

class RightrankCreateForm(forms.ModelForm):
    one = forms.ModelChoiceField(label='1位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                 empty_label='1位を選択')
    two = forms.ModelChoiceField(label='2位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                 empty_label='2位を選択')
    three = forms.ModelChoiceField(label='3位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                   empty_label='3位を選択')
    four = forms.ModelChoiceField(label='4位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                  empty_label='4位を選択')
    five = forms.ModelChoiceField(label='5位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                  empty_label='5位を選択')
    six = forms.ModelChoiceField(label='6位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                 empty_label='6位を選択')
    seven = forms.ModelChoiceField(label='7位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                   empty_label='7位を選択')
    eight = forms.ModelChoiceField(label='8位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                   empty_label='8位を選択')
    nine = forms.ModelChoiceField(label='9位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                  empty_label='9位を選択')
    ten = forms.ModelChoiceField(label='10位', queryset=RightPlayer.objects.all(), widget=forms.Select,
                                 empty_label='10位を選択')

    class Meta:
        model = RightRank

        fields = ('user', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',)
        widget = {'user': forms.TextInput(), }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs['class'] = 'form-control'
        self.fields['user'].widget.attrs['placeholder'] = '作成者'
        self.fields['user'].widget.attrs['maxlength'] = '20'

rizin_app/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from .models import BantamPlayer,FeatherPlayer,RightPlayer,BantamRank,FeatherRank,RightRank
from .forms import BantamrankCreateForm,FeatherrankCreateForm,RightrankCreateForm

class IndexView(generic.TemplateView):
    template_name = 'index.html'

def player_list(request):
    bantam_players = BantamPlayer.objects.all()
    feather_players = FeatherPlayer.objects.all()
    right_players = RightPlayer.objects.all()
    params = {
        'bantam_players': bantam_players,
        'feather_players': feather_players,
        'right_players': right_players,
    }
    return render(request,'player_list.html',params)


class BantamrankCreateView(generic.FormView):
    model = BantamRank
    template_name = 'bantamrank_create.html'
    form_class = BantamrankCreateForm
    success_url = reverse_lazy('rizin_app:bantamrank_list')

    def form_valid(self,form):
        bantamrank = form.save(commit=False)
        bantamrank.save()
        messages.success(self.request,'バンタム級ランキングを作成しました。')
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.success(self.request,'作成に失敗しました。')
        return super().form_invalid(form)


class FeatherrankCreateView(generic.FormView):
    model = FeatherRank
    template_name = 'featherrank_create.html'
    form_class = FeatherrankCreateForm
    success_url = reverse_lazy('rizin_app:featherrank_list')

    def form_valid(self,form):
        featherrank = form.save(commit=False)
        featherrank.save()
        messages.success(self.request,'フェザー級ランキングを作成しました。')
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.success(self.request,'作成に失敗しました。')
        return super().form_invalid(form)

class RightrankCreateView(generic.FormView):
    model = RightRank
    template_name = 'rightrank_create.html'
    form_class = RightrankCreateForm
    success_url = reverse_lazy('rizin_app:rightrank_list')

    def form_valid(self,form):
        rightrank = form.save(commit=False)
        rightrank.save()
        messages.success(self.request,'ライト級ランキングを作成しました。')
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.success(self.request,'作成に失敗しました。')
        return super().form_invalid(form)


class BantamrankListView(generic.ListView):
    model = BantamRank
    template_name = 'bantamrank_list.html'
    paginate_by = 2

    def get_queryset(self):
        bantamranks = BantamRank.objects.all().order_by('-created_at')
        return bantamranks

class FeatherrankListView(generic.ListView):
    model = FeatherRank
    template_name = 'featherrank_list.html'
    paginate_by = 3

    def get_queryset(self):
        featherranks = FeatherRank.objects.all().order_by('-created_at')
        return featherranks

class RightrankListView(generic.ListView):
    model = RightRank
    template_name = 'rightrank_list.html'
    paginate_by = 2

    def get_queryset(self):
        rightranks = RightRank.objects.all().order_by('-created_at')
        return rightranks

rizin_app/templates/bantamrank_careate.html
{% extends 'base.html' %}
{% load static %}

{% block title %}バンタム級ランキング作成 | rizin app{% endblock %}

{% block active_bantamrank_list %}active{% endblock %}

{% block contents %}
<hr>
<hr>
<h2 class="bantamrank-create-title">-----あなたが考えるRIZINバンタム級ランキングを作ろう！-----</h2>
<hr>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

rizin_app/templates/bantamrank_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}バンタム級ランキング作成 | rizin app{% endblock %}

{% block active_bantamrank_list %}active{% endblock %}

{% block contents %}
<hr>
<hr>
<h2 class="bantamrank-create-title">-----あなたが考えるRIZINバンタム級ランキングを作ろう！-----</h2>
<hr>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
                <button class="btn" type="submit"><a href="{% url 'rizin_app:bantamrank_list' %}">キャンセル</a></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

rizin_app/templates/base.html
{% load static %}
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- My style -->
        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    </head>
    <body id="page-top">
        <div id="wrapper">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
                <div class="container">
                    <a class="navbar-brand js-scroll-trigger" href="{% url 'rizin_app:index' %}">HOME</a>
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        Menu
                        <i class="fas fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'rizin_app:player_list' %}">FIGHTERS</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'rizin_app:bantamrank_list' %}">BANTAM RANK</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'rizin_app:featherrank_list' %}">FEATHER RANK</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'rizin_app:rightrank_list' %}">RIGHT RANK</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% block header %}{% endblock %}
            {% block contents %}{% endblock %}
            <!-- Footer-->
            <footer class="footer bg-black small text-center text-white-50"><div class="container">Copyright © rizin rank 2021</div></footer>
            <!-- Bootstrap core JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Third party plugin JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
            <!-- Core theme JS-->
            <script src="{% static 'js/scripts.js' %}"></script>
        </div>
    </body>
</html>

rizin_app/templates/featherrank_careate.html
{% extends 'base.html' %}
{% load static %}

{% block title %}フェザー級ランキング作成 | rizin app{% endblock %}

{% block active_featherrank_list %}active{% endblock %}

{% block contents %}
<hr>
<hr>
<h2 class="featherrank-create-title">-----あなたが考えるRIZINフェザー級ランキングを作ろう！-----</h2>
<hr>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

rizin_app/templates/featherrank_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}フェザー級ランキング作成 | rizin app{% endblock %}

{% block active_featherrank_list %}active{% endblock %}

{% block contents %}
<hr>
<hr>
<h2 class="featherrank-create-title">-----あなたが考えるRIZINフェザー級ランキングを作ろう！-----</h2>
<hr>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
                <button class="btn" type="submit"><a href="{% url 'rizin_app:featherrank_list' %}">キャンセル</a></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

rizin_app/templates/player_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}選手一覧 | rizin rank{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
{% endblock %}

{% block contents %}
    <div class="container">
        <h1 class="sub-title">選手一覧 | バンタム級</h1>
        <a href="{% url 'rizin_app:bantamrank_create' %}" class="btn btn-primary create-link">バンタム級ランキングを作成</a>
        <br>
        <div class="card-list">
            {% for player in bantam_players %}
                <div class="card" style="width: 10rem;">
                    <img src="{{ player.photo.url }}" class="card-img-top">
                    <div class="card-body">
                        <p class="card-text"><a href="https://jp.rizinff.com/_tags/{{ player.name }}" target="_blank" rel="noopener noreferrer">{{ player.name }}</a></p>
                    </div>
                </div>
            {% endfor %}
        </div>

        <h1 class="sub-title">選手一覧 | フェザー級</h1>
        <a href="{% url 'rizin_app:featherrank_create' %}" class="btn btn-primary create-link">フェザー級ランキングを作成</a>
        <br>
        <div class="card-list">
            {% for player in feather_players %}
                <div class="card" style="width: 10rem;">
                    <img src="{{ player.photo.url }}" class="card-img-top">
                    <div class="card-body">
                    <p class="card-text"><a href="https://jp.rizinff.com/_tags/{{ player.name }}" target="_blank" rel="noopener noreferrer">{{ player.name }}</a></p>
                    </div>
                </div>
            {% endfor %}
        </div>

        <h1 class="sub-title">選手一覧 | ライト級</h1>
        <a href="{% url 'rizin_app:rightrank_create' %}" class="btn btn-primary create-link">ライト級ランキングを作成</a>
        <br>
        <div class="card-list">
            {% for player in right_players %}
                <div class="card" style="width: 10rem;">
                    <img src="{{ player.photo.url }}" class="card-img-top">
                    <div class="card-body">
                    <p class="card-text"><a href="https://jp.rizinff.com/_tags/{{ player.name }}" target="_blank" rel="noopener noreferrer">{{ player.name }}</a></p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

rizin_app/templates/rightrank_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ライト級ランキング作成 | rizin app{% endblock %}

{% block active_rightrank_list %}active{% endblock %}

{% block contents %}
<hr>
<hr>
<h2 class="rightrank-create-title">-----あなたが考えるRIZINライト級ランキングを作ろう！-----</h2>
<hr>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
                <button class="btn" type="submit"><a href="{% url 'rizin_app:rightrank_list' %}">キャンセル</a></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}